authors:
  totto:
    name: Thor Henning Hetland
    description: Founder of JavaZone, Chairman of IASA, Java Champion, Founder of eXOReaction
    avatar: https://wiki.totto.org/assets/images/totto-2014.jpg
