#!/usr/bin/env python3
"""Generate knowledge/blog.yaml (KCP manifest) and includes/latest-posts.md
(home-page snippet) from MkDocs blog post front matter.

URLs are built with the SAME slugify Material uses (pymdownx slugify on the
title, or a front-matter `slug:` override), so they match the published pages
byte-for-byte — not the filename, which can differ from the title slug."""

import os
import re
import sys
import yaml
from pathlib import Path
from datetime import date as Date, datetime
from pymdownx.slugs import slugify as _mk_slugify

POSTS_DIR   = Path("docs/blog/posts")
OUTPUT      = Path("docs/knowledge/blog.yaml")
SNIPPET_OUT = Path("includes/latest-posts.md")
BASE_URL    = "https://wiki.totto.org"
LATEST_N    = 3

# Same callable Material's blog plugin uses: slugify(case="lower"), separator "-"
_slugify = _mk_slugify(case="lower")

# The published URL is normally slugify(title) — or a front-matter `slug:`.
# A few legacy posts resolved to a slug Material derived differently (filename,
# or a hand-set slug that predates the title). Pin those to their live URLs so
# the manifest never points at a 404. Keyed by post filename.
SLUG_OVERRIDES = {
    "2026-03-02-kcp-commands.md":            "kcp-commands",
    "2026-06-12-kcp-0.18-unit-integrity.md": "2026-06-12-kcp-018-unit-integrity",
}

# First category -> Material icon for the home cards
CATEGORY_ICON = {
    "Knowledge Infrastructure":        "material-database-outline",
    "Knowledge Context Protocol":      "material-map-marker-path",
    "AI-Augmented Development":         "material-rocket-launch-outline",
    "AI Agents & the Agentic Web":     "material-robot-outline",
    "Governance, Trust & Compliance":  "material-shield-check-outline",
    "Software Architecture":           "material-vector-arrange-below",
    "Cloud Computing":                 "material-cloud-outline",
    "Career & Community":              "material-account-group-outline",
    "Quantum Computing":               "material-atom",
}
DEFAULT_ICON = "material-post-outline"

def extract_front_matter(text):
    """Return (front_matter_dict, body) or (None, text) if no front matter."""
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)", text, re.DOTALL)
    if not m:
        return None, text
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        fm = {}
    return fm, m.group(2)

def extract_title(body):
    """Extract first # heading from post body."""
    m = re.search(r"^#\s+(.+)$", body, re.MULTILINE)
    return m.group(1).strip() if m else None

def slug_from_filename(filename):
    """2026-05-07-my-post.md → my-post"""
    return re.sub(r"^\d{4}-\d{2}-\d{2}-", "", filename[:-3])

def url_from_post(filename, title, slug_override):
    """Build the published URL the way Material does: date from filename,
    slug from the title (or an explicit front-matter `slug:`)."""
    m = re.match(r"(\d{4})-(\d{2})-(\d{2})-", filename)
    if not m:
        return None
    y, mo, d = m.groups()
    slug = SLUG_OVERRIDES.get(filename) or slug_override or _slugify(title, "-")
    return f"/blog/{y}/{mo}/{d}/{slug}/"

def format_date(raw):
    """'2026-07-15T09:00:00' / datetime / date → 'July 15, 2026'."""
    if isinstance(raw, datetime):
        return raw.strftime("%B %-d, %Y")
    if isinstance(raw, Date):
        return raw.strftime("%B %-d, %Y")
    s = str(raw)
    m = re.match(r"(\d{4})-(\d{2})-(\d{2})", s)
    if not m:
        return s
    try:
        return datetime(int(m.group(1)), int(m.group(2)), int(m.group(3))).strftime("%B %-d, %Y")
    except ValueError:
        return s

def shorten(text, limit=155):
    text = " ".join(str(text).split())
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0].rstrip(",.;:—- ")
    return cut + "…"

def write_latest_snippet(posts):
    """Emit the home-page 'Recent writing' cards for the newest LATEST_N posts."""
    cards = ['<div class="grid cards" markdown>', ""]
    for p in posts[:LATEST_N]:
        icon = DEFAULT_ICON
        for c in (p.get("categories") or []):
            if c in CATEGORY_ICON:
                icon = CATEGORY_ICON[c]
                break
        desc = shorten(p.get("description") or p["title"])
        cards.append(f"-   :{icon}:{{ .card-icon }} **[{p['title']}]({p['url_path']})**")
        cards.append("")
        cards.append("    ---")
        cards.append("")
        cards.append(f"    {desc}")
        cards.append("")
        cards.append(f'    <span class="card-meta">{p["date_human"]}</span>')
        cards.append("")
    cards.append("</div>")
    SNIPPET_OUT.parent.mkdir(parents=True, exist_ok=True)
    SNIPPET_OUT.write_text(
        "<!-- AUTO-GENERATED by scripts/generate-blog-manifest.py — do not edit -->\n"
        + "\n".join(cards) + "\n",
        encoding="utf-8",
    )
    print(f"Generated {SNIPPET_OUT} with {min(LATEST_N, len(posts))} cards.")

def main():
    posts = []
    for path in sorted(POSTS_DIR.glob("*.md"), reverse=True):
        text = path.read_text(encoding="utf-8")
        fm, body = extract_front_matter(text)
        if fm is None:
            continue

        title = extract_title(body) or fm.get("title") or path.stem
        url   = url_from_post(path.name, title, fm.get("slug"))
        if not url:
            continue

        post = {
            "title": title,
            "date":  str(fm.get("date", "")),
            "url":   f"{BASE_URL}{url}",
            # extras used only for the home snippet (not written to blog.yaml)
            "url_path":   url,
            "date_human": format_date(fm.get("date", "")),
            "description": fm.get("description"),
        }
        if fm.get("categories"):
            post["categories"] = list(fm["categories"])
        if fm.get("tags"):
            post["tags"] = list(fm["tags"])

        posts.append(post)

    # Sort newest-first by the actual date/time (matches the Material feed order,
    # which filename sort does not when several posts share a day).
    def _date_key(p):
        s = str(p.get("date", ""))
        for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d"):
            try:
                return datetime.strptime(s[:19] if "T" in s or " " in s else s[:10], fmt)
            except ValueError:
                continue
        return datetime.min
    posts.sort(key=_date_key, reverse=True)

    write_latest_snippet(posts)

    manifest = {
        "# wiki.totto.org — blog index (auto-generated)": None,
        "# DO NOT EDIT — regenerated by scripts/generate-blog-manifest.py": None,
    }

    # Build clean YAML manually to avoid anchors / aliases
    header = (
        "# wiki.totto.org — blog index (auto-generated)\n"
        "# DO NOT EDIT — regenerated by .github/workflows/kcp-manifests.yml\n"
        f"# Posts: {len(posts)} | Generated: {Date.today().isoformat()}\n"
        "version: \"0.21\"\n\n"
        "id: blog\n"
        "parent: https://wiki.totto.org/knowledge.yaml\n\n"
        "discovery:\n"
        "  provenance: canonical\n"
        "  confidence: high\n"
        "  staleness_days: 1\n"
        "  generated_by: scripts/generate-blog-manifest.py\n\n"
        "signing:\n"
        "  scheme: ed25519\n"
        "  scope: this-manifest\n"
        "  public_key: https://wiki.totto.org/.well-known/kcp-signing-key.pub\n"
        "  signature: https://wiki.totto.org/knowledge/blog.yaml.sig\n\n"
        f"post_count: {len(posts)}\n\n"
        "posts:\n"
    )

    post_lines = []
    for p in posts:
        post_lines.append(f"  - title: {yaml.dump(p['title'], default_flow_style=True).strip()}")
        post_lines.append(f"    date: \"{p['date']}\"")
        post_lines.append(f"    url: {p['url']}")
        if p.get("categories"):
            post_lines.append(f"    categories: {yaml.dump(p['categories'], default_flow_style=True).strip()}")
        if p.get("tags"):
            post_lines.append(f"    tags: {yaml.dump(p['tags'], default_flow_style=True).strip()}")
        post_lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header + "\n".join(post_lines) + "\n", encoding="utf-8")
    print(f"Generated {OUTPUT} with {len(posts)} posts.")

if __name__ == "__main__":
    main()
