#!/usr/bin/env python3
"""Generate knowledge/blog.yaml from MkDocs blog post front matter."""

import os
import re
import sys
import yaml
from pathlib import Path
from datetime import date as Date

POSTS_DIR = Path("docs/blog/posts")
OUTPUT    = Path("docs/knowledge/blog.yaml")
BASE_URL  = "https://wiki.totto.org"

def extract_front_matter(text):
    """Return (front_matter_dict, body) or (None, text) if no front matter."""
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)", text, re.DOTALL)
    if not m:
        return None, text
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        fm = {}
    return fm, m.group(2)

def extract_title(body):
    """Extract first # heading from post body."""
    m = re.search(r"^#\s+(.+)$", body, re.MULTILINE)
    return m.group(1).strip() if m else None

def slug_from_filename(filename):
    """2026-05-07-my-post.md → my-post"""
    return re.sub(r"^\d{4}-\d{2}-\d{2}-", "", filename[:-3])

def url_from_filename(filename):
    """2026-05-07-my-post.md → /blog/2026/05/07/my-post/"""
    m = re.match(r"(\d{4})-(\d{2})-(\d{2})-(.+)\.md$", filename)
    if not m:
        return None
    y, mo, d, slug = m.groups()
    return f"/blog/{y}/{mo}/{d}/{slug}/"

def main():
    posts = []
    for path in sorted(POSTS_DIR.glob("*.md"), reverse=True):
        text = path.read_text(encoding="utf-8")
        fm, body = extract_front_matter(text)
        if fm is None:
            continue

        title = extract_title(body)
        url   = url_from_filename(path.name)
        if not url:
            continue

        post = {
            "title": title or path.stem,
            "date":  str(fm.get("date", "")),
            "url":   f"{BASE_URL}{url}",
        }
        if fm.get("categories"):
            post["categories"] = list(fm["categories"])
        if fm.get("tags"):
            post["tags"] = list(fm["tags"])

        posts.append(post)

    manifest = {
        "# wiki.totto.org — blog index (auto-generated)": None,
        "# DO NOT EDIT — regenerated by scripts/generate-blog-manifest.py": None,
    }

    # Build clean YAML manually to avoid anchors / aliases
    header = (
        "# wiki.totto.org — blog index (auto-generated)\n"
        "# DO NOT EDIT — regenerated by .github/workflows/kcp-manifests.yml\n"
        f"# Posts: {len(posts)} | Generated: {Date.today().isoformat()}\n"
        "version: \"0.14\"\n\n"
        "id: blog\n"
        "parent: https://wiki.totto.org/knowledge.yaml\n\n"
        "discovery:\n"
        "  provenance: canonical\n"
        "  confidence: high\n"
        "  staleness_days: 1\n"
        "  generated_by: scripts/generate-blog-manifest.py\n\n"
        "signing:\n"
        "  scheme: ed25519\n"
        "  scope: this-manifest\n"
        "  public_key: https://wiki.totto.org/.well-known/kcp-signing-key.pub\n"
        "  signature: https://wiki.totto.org/knowledge/blog.yaml.sig\n\n"
        f"post_count: {len(posts)}\n\n"
        "posts:\n"
    )

    post_lines = []
    for p in posts:
        post_lines.append(f"  - title: {yaml.dump(p['title'], default_flow_style=True).strip()}")
        post_lines.append(f"    date: \"{p['date']}\"")
        post_lines.append(f"    url: {p['url']}")
        if p.get("categories"):
            post_lines.append(f"    categories: {yaml.dump(p['categories'], default_flow_style=True).strip()}")
        if p.get("tags"):
            post_lines.append(f"    tags: {yaml.dump(p['tags'], default_flow_style=True).strip()}")
        post_lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header + "\n".join(post_lines) + "\n", encoding="utf-8")
    print(f"Generated {OUTPUT} with {len(posts)} posts.")

if __name__ == "__main__":
    main()
